# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Services_2.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QMessageBox
from employers import *
import csv
from employers import *



class Service_info:
    def __init__(self, name, price, point):
        self.name= name
        self.price= price
        self.point= point

    def get_name(self):
        return self.name

    def get_price(self):
        return self.price

    def get_point(self):
        return self.point


s1= Service_info('Cooking', 35000, 6) #per food
s2= Service_info('Catering', 20000, 3) #per hour
s3= Service_info('House Cleaning', 15000, 2) #per hour
s4= Service_info('Building Cleaning', 19000, 3) #per hour
s5= Service_info('Laundry', 10000, 1) #minimum per cloth
s6= Service_info('Indoor Spraying', 20000, 5) #per hour
s7= Service_info('Cooling System', 350000, 7) #per system
s8= Service_info('Heating System', 80000, 7) #per system
s9= Service_info('Water Plumbing', 100000, 4) #per hour
s10= Service_info('Gas Plumbing', 150000, 6) #per hour
s11= Service_info('Water Refinary', 120000, 4) #per system
s12= Service_info('Installing/Repairing Big Appliance', 80000, 4) #per system
s13= Service_info('Building', 250000, 7) #per day
s14= Service_info('Woodworking', 250000, 7) #per piece
s15= Service_info('Parquet/Wallpaper', 90000, 3) #per m^2
s16= Service_info('Ceramic/Tile', 120000, 3) #per m^2
s17= Service_info('Plastering', 250000, 4) #per day
s18= Service_info('Painting', 250000, 3) #per day
s19= Service_info('Smithery and Welding', 300000, 7) #per day
s20= Service_info('Door And Window', 100000, 3) #each window/door
s21= Service_info('Interior Design', 200000, 8) #per room
s21= Service_info('Outdoor Spraying', 26000, 5) #per hour
s22= Service_info('Outdoor Design', 250000, 8)
s23= Service_info('Gardening', 15000, 4) #per hour
s24= Service_info('Laptop Repiring', 50000, 7) #per system
s25= Service_info('Tablet/Mobile Repairing', 50000, 7) 
s26= Service_info('Game Console Repairing', 70000, 7)
s27= Service_info('Wiring', 250000, 7) #per day
s28= Service_info('Installing/Repairing Generators', 300000, 5) #per day
s29= Service_info('Security Alarms', 80000, 5) #per system
s30= Service_info('Security Cameras', 80000, 5) #per system
s31= Service_info('Fixing Cars', 100000, 4) #per car
s32= Service_info('Car Wash', 30000, 1)
s33= Service_info('Moving Out Furniture', 35000, 3) #per hour
s34= Service_info('Package Delivery', 15000, 2) #per hour
s35= Service_info('Sewing', 120000, 6) #minimum
s36= Service_info('Cloth Restoration', 20000, 5) #minimum 
s37= Service_info('Hair', 50000, 6) #minimum
s38= Service_info('Makeup', 80000, 7) #minimum per hour
s39= Service_info('Nails', 100000, 6)
s40= Service_info('Injections/ Bandages/ Stiches', 25000, 7) #minimum
s41= Service_info('Nanny', 80000, 7) #per day
s42= Service_info('Elderly Care', 90000, 8) #per day
s43= Service_info('Patient Care', 90000, 9) #per day
s44= Service_info('Pet Grooming', 140000, 7) #per pet
s45= Service_info('Pet  Walking', 45000, 2) #per hour
s46= Service_info('Pet Training', 80000, 9) #per hour
s47= Service_info('Vet', 200000, 10)
s48= Service_info('Teaching All Grades', 50000, 10) #minimum per hour
s49= Service_info('Enterance Exam', 120000, 10) #minimum per hour(depends on the course)
s50= Service_info('Teaaching University Courses', 130000, 10) #minimum per hour(depends on the course)
s51= Service_info('Teaching Music', 200000, 10) #per hour
s52= Service_info('Teaching Software', 140000, 10) #minimum per hour(depends on the software)
s53= Service_info('Law', 150000, 10) #per hour
s54= Service_info('Graduation', 50000, 10) #per hour
s55= Service_info('Psychology', 180000, 10) #per hour
s56= Service_info('Diet', 100000, 10) #per hour
s57= Service_info('Fingerfood', 100000, 6)
s58= Service_info('Photo', 160000, 9) #per hour
s59= Service_info('Musicians', 200000, 9) #per hour
s60= Service_info('Key', 50000, 7) #per key
s61= Service_info('Disinfect', 130000, 9) #per room
s62= Service_info('Lab Test', 50000, 9)
s63= Service_info('Opening Doors', 15000, 7)
s64= Service_info('other', 50000, 5)
sall= [s1]+[s2]+[s3]+[s4]+[s5]+[s6]+[s7]+[s8]+[s9]+[s10]+[s11]+[s12]+[s13]+[s14]+[s15]+[s16]+[s17]+[s18]+[s19]+[s20]+[s21]+[s22]+[s23]+[s24]+[s25]+[s26]+[s27]+[s28]+[s29]+[s30]+[s31]+[s32]+[s33]+[s34]+[s35]+[s36]+[s37]+[s38]+[s39]+[s40]+[s41]+[s42]+[s43]+[s44]+[s45]+[s46]+[s47]+[s48]+[s49]+[s50]+[s51]+[s52]+[s53]+[s54]+[s55]+[s56]+[s57]+[s58]+[s59]+[s60]+[s61]+[s62]+[s63]+[s64]


class Ui_Services_2(object):
    
    def setupUi(self, Services_2,username):
        self.username=username
        Services_2.setObjectName("Services_2")
        Services_2.resize(1000, 816)
        Services_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Services_2)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.clean = QtWidgets.QWidget()
        self.clean.setObjectName("clean")
        self.gridLayout = QtWidgets.QGridLayout(self.clean)
        self.gridLayout.setObjectName("gridLayout")
        self.cooking = QtWidgets.QCheckBox(self.clean)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cooking.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pics/cooking.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cooking.setIcon(icon)
        self.cooking.setIconSize(QtCore.QSize(30, 30))
        self.cooking.setObjectName("cooking")
        self.gridLayout.addWidget(self.cooking, 0, 0, 1, 1)
        self.hcleaning = QtWidgets.QCheckBox(self.clean)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hcleaning.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pics/cleaning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hcleaning.setIcon(icon1)
        self.hcleaning.setIconSize(QtCore.QSize(30, 30))
        self.hcleaning.setObjectName("hcleaning")
        self.gridLayout.addWidget(self.hcleaning, 0, 1, 1, 1)
        self.bcleaning = QtWidgets.QCheckBox(self.clean)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bcleaning.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pics/broom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bcleaning.setIcon(icon2)
        self.bcleaning.setIconSize(QtCore.QSize(30, 30))
        self.bcleaning.setObjectName("bcleaning")
        self.gridLayout.addWidget(self.bcleaning, 1, 1, 1, 1)
        self.inspraying = QtWidgets.QCheckBox(self.clean)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.inspraying.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Pics/spraying.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inspraying.setIcon(icon3)
        self.inspraying.setIconSize(QtCore.QSize(30, 30))
        self.inspraying.setObjectName("inspraying")
        self.gridLayout.addWidget(self.inspraying, 2, 1, 1, 1)
        self.catering = QtWidgets.QCheckBox(self.clean)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.catering.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Pics/buffet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.catering.setIcon(icon4)
        self.catering.setIconSize(QtCore.QSize(30, 30))
        self.catering.setObjectName("catering")
        self.gridLayout.addWidget(self.catering, 1, 0, 1, 1)
        self.laundry = QtWidgets.QCheckBox(self.clean)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.laundry.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Pics/washing-machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.laundry.setIcon(icon5)
        self.laundry.setIconSize(QtCore.QSize(30, 30))
        self.laundry.setObjectName("laundry")
        self.gridLayout.addWidget(self.laundry, 2, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Pics/dust.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.clean, icon6, "")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cool = QtWidgets.QCheckBox(self.home)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Pics/fan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cool.setIcon(icon7)
        self.cool.setIconSize(QtCore.QSize(25, 25))
        self.cool.setObjectName("cool")
        self.gridLayout_2.addWidget(self.cool, 0, 0, 1, 1)
        self.water = QtWidgets.QCheckBox(self.home)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Pics/clog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.water.setIcon(icon8)
        self.water.setIconSize(QtCore.QSize(30, 30))
        self.water.setObjectName("water")
        self.gridLayout_2.addWidget(self.water, 0, 1, 1, 1)
        self.gas = QtWidgets.QCheckBox(self.home)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Pics/gas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gas.setIcon(icon9)
        self.gas.setIconSize(QtCore.QSize(30, 30))
        self.gas.setObjectName("gas")
        self.gridLayout_2.addWidget(self.gas, 1, 1, 1, 1)
        self.heat = QtWidgets.QCheckBox(self.home)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Pics/system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.heat.setIcon(icon10)
        self.heat.setIconSize(QtCore.QSize(25, 25))
        self.heat.setObjectName("heat")
        self.gridLayout_2.addWidget(self.heat, 1, 0, 1, 1)
        self.refinary = QtWidgets.QCheckBox(self.home)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Pics/water.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refinary.setIcon(icon11)
        self.refinary.setIconSize(QtCore.QSize(25, 25))
        self.refinary.setObjectName("refinary")
        self.gridLayout_2.addWidget(self.refinary, 0, 2, 1, 1)
        self.bigappliance = QtWidgets.QCheckBox(self.home)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Pics/refrigerator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bigappliance.setIcon(icon12)
        self.bigappliance.setIconSize(QtCore.QSize(30, 30))
        self.bigappliance.setObjectName("bigappliance")
        self.gridLayout_2.addWidget(self.bigappliance, 1, 2, 1, 1)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Pics/appliances.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.home, icon13, "")
        self.decor = QtWidgets.QWidget()
        self.decor.setObjectName("decor")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.decor)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.building = QtWidgets.QCheckBox(self.decor)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Pics/toolbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.building.setIcon(icon14)
        self.building.setIconSize(QtCore.QSize(30, 30))
        self.building.setObjectName("building")
        self.gridLayout_3.addWidget(self.building, 0, 0, 1, 1)
        self.welding = QtWidgets.QCheckBox(self.decor)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Pics/welder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.welding.setIcon(icon15)
        self.welding.setIconSize(QtCore.QSize(30, 30))
        self.welding.setObjectName("welding")
        self.gridLayout_3.addWidget(self.welding, 2, 1, 1, 1)
        self.painting = QtWidgets.QCheckBox(self.decor)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Pics/painting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.painting.setIcon(icon16)
        self.painting.setIconSize(QtCore.QSize(30, 30))
        self.painting.setObjectName("Pics/painting")
        self.gridLayout_3.addWidget(self.painting, 1, 1, 1, 1)
        self.parquet = QtWidgets.QCheckBox(self.decor)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Pics/wallpaper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.parquet.setIcon(icon17)
        self.parquet.setIconSize(QtCore.QSize(30, 30))
        self.parquet.setObjectName("parquet")
        self.gridLayout_3.addWidget(self.parquet, 2, 0, 1, 1)
        self.plastering = QtWidgets.QCheckBox(self.decor)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Pics/plaster.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plastering.setIcon(icon18)
        self.plastering.setIconSize(QtCore.QSize(30, 30))
        self.plastering.setObjectName("plastering")
        self.gridLayout_3.addWidget(self.plastering, 0, 1, 1, 1)
        self.wood = QtWidgets.QCheckBox(self.decor)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Pics/saw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wood.setIcon(icon19)
        self.wood.setIconSize(QtCore.QSize(30, 30))
        self.wood.setObjectName("wood")
        self.gridLayout_3.addWidget(self.wood, 1, 0, 1, 1)
        self.door = QtWidgets.QCheckBox(self.decor)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Pics/window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.door.setIcon(icon20)
        self.door.setIconSize(QtCore.QSize(30, 30))
        self.door.setObjectName("door")
        self.gridLayout_3.addWidget(self.door, 3, 1, 1, 1)
        self.ceramic = QtWidgets.QCheckBox(self.decor)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("Pics/floor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ceramic.setIcon(icon21)
        self.ceramic.setIconSize(QtCore.QSize(30, 30))
        self.ceramic.setObjectName("ceramic")
        self.gridLayout_3.addWidget(self.ceramic, 3, 0, 1, 1)
        self.interior_d = QtWidgets.QCheckBox(self.decor)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("Pics/interior-design.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.interior_d.setIcon(icon22)
        self.interior_d.setIconSize(QtCore.QSize(30, 30))
        self.interior_d.setObjectName("interior_d")
        self.gridLayout_3.addWidget(self.interior_d, 0, 2, 1, 1)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("Pics/decor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.decor, icon23, "")
        self.garden = QtWidgets.QWidget()
        self.garden.setObjectName("garden")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.garden)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outspraying = QtWidgets.QCheckBox(self.garden)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("Pics/fertilizer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.outspraying.setIcon(icon24)
        self.outspraying.setIconSize(QtCore.QSize(40, 40))
        self.outspraying.setObjectName("outspraying")
        self.horizontalLayout_4.addWidget(self.outspraying)
        self.outdoor_d = QtWidgets.QCheckBox(self.garden)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("Pics/fountain.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.outdoor_d.setIcon(icon25)
        self.outdoor_d.setIconSize(QtCore.QSize(40, 40))
        self.outdoor_d.setObjectName("outdoor_d")
        self.horizontalLayout_4.addWidget(self.outdoor_d)
        self.gardening = QtWidgets.QCheckBox(self.garden)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("Pics/garden.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gardening.setIcon(icon26)
        self.gardening.setIconSize(QtCore.QSize(40, 40))
        self.gardening.setObjectName("gardening")
        self.horizontalLayout_4.addWidget(self.gardening)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("Pics/gardening.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.garden, icon27, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.digital = QtWidgets.QWidget()
        self.digital.setObjectName("digital")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.digital)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.laptop = QtWidgets.QCheckBox(self.digital)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.laptop.setFont(font)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("Pics/wrench.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.laptop.setIcon(icon28)
        self.laptop.setIconSize(QtCore.QSize(40, 40))
        self.laptop.setObjectName("laptop")
        self.horizontalLayout_8.addWidget(self.laptop)
        self.tablet = QtWidgets.QCheckBox(self.digital)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tablet.setFont(font)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("Pics/function.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tablet.setIcon(icon29)
        self.tablet.setIconSize(QtCore.QSize(40, 40))
        self.tablet.setObjectName("tablet")
        self.horizontalLayout_8.addWidget(self.tablet)
        self.game = QtWidgets.QCheckBox(self.digital)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.game.setFont(font)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("Pics/ps4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.game.setIcon(icon30)
        self.game.setIconSize(QtCore.QSize(40, 40))
        self.game.setObjectName("game")
        self.horizontalLayout_8.addWidget(self.game)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("Pics/laptop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.digital, icon31, "")
        self.elctric = QtWidgets.QWidget()
        self.elctric.setObjectName("elctric")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.elctric)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.wire = QtWidgets.QCheckBox(self.elctric)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap("Pics/wire.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wire.setIcon(icon32)
        self.wire.setIconSize(QtCore.QSize(35, 35))
        self.wire.setObjectName("wire")
        self.horizontalLayout_6.addWidget(self.wire)
        self.generator = QtWidgets.QCheckBox(self.elctric)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap("Pics/electricity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generator.setIcon(icon33)
        self.generator.setIconSize(QtCore.QSize(35, 35))
        self.generator.setObjectName("generator")
        self.horizontalLayout_6.addWidget(self.generator)
        self.s_alarm = QtWidgets.QCheckBox(self.elctric)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap("Pics/padlock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.s_alarm.setIcon(icon34)
        self.s_alarm.setIconSize(QtCore.QSize(35, 35))
        self.s_alarm.setObjectName("s_alarm")
        self.horizontalLayout_6.addWidget(self.s_alarm)
        self.s_camera = QtWidgets.QCheckBox(self.elctric)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap("Pics/cctv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.s_camera.setIcon(icon35)
        self.s_camera.setIconSize(QtCore.QSize(40, 40))
        self.s_camera.setObjectName("s_camera")
        self.horizontalLayout_6.addWidget(self.s_camera)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap("Pics/energy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.elctric, icon36, "")
        self.car = QtWidgets.QWidget()
        self.car.setObjectName("car")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.car)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fix_car = QtWidgets.QCheckBox(self.car)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap("Pics/car-repair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fix_car.setIcon(icon37)
        self.fix_car.setIconSize(QtCore.QSize(50, 45))
        self.fix_car.setObjectName("fix_car")
        self.horizontalLayout_2.addWidget(self.fix_car)
        self.carwash = QtWidgets.QCheckBox(self.car)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap("Pics/carwash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.carwash.setIcon(icon38)
        self.carwash.setIconSize(QtCore.QSize(50, 50))
        self.carwash.setObjectName("carwash")
        self.horizontalLayout_2.addWidget(self.carwash)
        self.label = QtWidgets.QLabel(self.car)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap("Pics/sedan-car-model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.car, icon39, "")
        self.shipment = QtWidgets.QWidget()
        self.shipment.setObjectName("shipment")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.shipment)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.furniture = QtWidgets.QCheckBox(self.shipment)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap("Pics/sofa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.furniture.setIcon(icon40)
        self.furniture.setIconSize(QtCore.QSize(50, 45))
        self.furniture.setObjectName("furniture")
        self.horizontalLayout_9.addWidget(self.furniture)
        self.delivery = QtWidgets.QCheckBox(self.shipment)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap("Pics/box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delivery.setIcon(icon41)
        self.delivery.setIconSize(QtCore.QSize(35, 35))
        self.delivery.setObjectName("delivery")
        self.horizontalLayout_9.addWidget(self.delivery)
        self.label_3 = QtWidgets.QLabel(self.shipment)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap("Pics/truck.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.shipment, icon42, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.clothes = QtWidgets.QWidget()
        self.clothes.setObjectName("clothes")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.clothes)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sewing = QtWidgets.QCheckBox(self.clothes)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sewing.setFont(font)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap("Pics/blouse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sewing.setIcon(icon43)
        self.sewing.setIconSize(QtCore.QSize(30, 30))
        self.sewing.setObjectName("sewing")
        self.horizontalLayout.addWidget(self.sewing)
        self.restoration = QtWidgets.QCheckBox(self.clothes)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.restoration.setFont(font)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap("Pics/sewing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoration.setIcon(icon44)
        self.restoration.setIconSize(QtCore.QSize(30, 30))
        self.restoration.setObjectName("restoration")
        self.horizontalLayout.addWidget(self.restoration)
        self.label_2 = QtWidgets.QLabel(self.clothes)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap("Pics/sewing-machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.clothes, icon45, "")
        self.beauty = QtWidgets.QWidget()
        self.beauty.setObjectName("beauty")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.beauty)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.hair = QtWidgets.QCheckBox(self.beauty)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap("Pics/hair-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hair.setIcon(icon46)
        self.hair.setIconSize(QtCore.QSize(40, 40))
        self.hair.setObjectName("hair")
        self.horizontalLayout_5.addWidget(self.hair)
        self.makeup = QtWidgets.QCheckBox(self.beauty)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap("Pics/eye-makeup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.makeup.setIcon(icon47)
        self.makeup.setIconSize(QtCore.QSize(42, 40))
        self.makeup.setObjectName("makeup")
        self.horizontalLayout_5.addWidget(self.makeup)
        self.nails = QtWidgets.QCheckBox(self.beauty)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap("Pics/nail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nails.setIcon(icon48)
        self.nails.setIconSize(QtCore.QSize(35, 35))
        self.nails.setObjectName("nails")
        self.horizontalLayout_5.addWidget(self.nails)
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap("Pics/furniture-and-household.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.beauty, icon49, "")
        self.medical = QtWidgets.QWidget()
        self.medical.setObjectName("medical")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.medical)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.injection = QtWidgets.QCheckBox(self.medical)
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap("Pics/injection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.injection.setIcon(icon50)
        self.injection.setIconSize(QtCore.QSize(35, 35))
        self.injection.setObjectName("injection")
        self.gridLayout_4.addWidget(self.injection, 0, 0, 1, 1)
        self.elder = QtWidgets.QCheckBox(self.medical)
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap("Pics/physiotherapy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.elder.setIcon(icon51)
        self.elder.setIconSize(QtCore.QSize(35, 35))
        self.elder.setObjectName("elder")
        self.gridLayout_4.addWidget(self.elder, 0, 1, 1, 1)
        self.nanny = QtWidgets.QCheckBox(self.medical)
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap("Pics/icons8-mother-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nanny.setIcon(icon52)
        self.nanny.setIconSize(QtCore.QSize(35, 35))
        self.nanny.setObjectName("nanny")
        self.gridLayout_4.addWidget(self.nanny, 1, 0, 1, 1)
        self.patient = QtWidgets.QCheckBox(self.medical)
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap("Pics/nurse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patient.setIcon(icon53)
        self.patient.setIconSize(QtCore.QSize(35, 35))
        self.patient.setObjectName("patient")
        self.gridLayout_4.addWidget(self.patient, 1, 1, 1, 1)
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap("Pics/shield.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.medical, icon54, "")
        self.pets = QtWidgets.QWidget()
        self.pets.setObjectName("pets")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pets)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.grooming = QtWidgets.QCheckBox(self.pets)
        icon55 = QtGui.QIcon()
        icon55.addPixmap(QtGui.QPixmap("Pics/beauty-saloon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.grooming.setIcon(icon55)
        self.grooming.setIconSize(QtCore.QSize(40, 40))
        self.grooming.setObjectName("grooming")
        self.horizontalLayout_3.addWidget(self.grooming)
        self.walking = QtWidgets.QCheckBox(self.pets)
        icon56 = QtGui.QIcon()
        icon56.addPixmap(QtGui.QPixmap("Pics/dog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.walking.setIcon(icon56)
        self.walking.setIconSize(QtCore.QSize(40, 40))
        self.walking.setObjectName("walking")
        self.horizontalLayout_3.addWidget(self.walking)
        self.train = QtWidgets.QCheckBox(self.pets)
        icon57 = QtGui.QIcon()
        icon57.addPixmap(QtGui.QPixmap("Pics/train.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.train.setIcon(icon57)
        self.train.setIconSize(QtCore.QSize(40, 40))
        self.train.setObjectName("train")
        self.horizontalLayout_3.addWidget(self.train)
        self.vet = QtWidgets.QCheckBox(self.pets)
        icon58 = QtGui.QIcon()
        icon58.addPixmap(QtGui.QPixmap("Pics/veterinary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vet.setIcon(icon58)
        self.vet.setIconSize(QtCore.QSize(40, 40))
        self.vet.setObjectName("vet")
        self.horizontalLayout_3.addWidget(self.vet)
        icon59 = QtGui.QIcon()
        icon59.addPixmap(QtGui.QPixmap("Pics/pet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.pets, icon59, "")
        self.verticalLayout.addWidget(self.tabWidget_3)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.education = QtWidgets.QWidget()
        self.education.setObjectName("education")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.education)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.all_grades = QtWidgets.QCheckBox(self.education)
        icon60 = QtGui.QIcon()
        icon60.addPixmap(QtGui.QPixmap("Pics/study.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.all_grades.setIcon(icon60)
        self.all_grades.setIconSize(QtCore.QSize(35, 35))
        self.all_grades.setObjectName("all_grades")
        self.gridLayout_6.addWidget(self.all_grades, 0, 0, 1, 1)
        self.software = QtWidgets.QCheckBox(self.education)
        icon61 = QtGui.QIcon()
        icon61.addPixmap(QtGui.QPixmap("Pics/algorithm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.software.setIcon(icon61)
        self.software.setIconSize(QtCore.QSize(35, 35))
        self.software.setObjectName("software")
        self.gridLayout_6.addWidget(self.software, 0, 2, 1, 1)
        self.enterance = QtWidgets.QCheckBox(self.education)
        icon62 = QtGui.QIcon()
        icon62.addPixmap(QtGui.QPixmap("Pics/exam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enterance.setIcon(icon62)
        self.enterance.setIconSize(QtCore.QSize(35, 35))
        self.enterance.setObjectName("enterance")
        self.gridLayout_6.addWidget(self.enterance, 1, 0, 1, 1)
        self.university = QtWidgets.QCheckBox(self.education)
        icon63 = QtGui.QIcon()
        icon63.addPixmap(QtGui.QPixmap("Pics/uni.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.university.setIcon(icon63)
        self.university.setIconSize(QtCore.QSize(35, 35))
        self.university.setObjectName("university")
        self.gridLayout_6.addWidget(self.university, 0, 1, 1, 1)
        self.music = QtWidgets.QCheckBox(self.education)
        icon64 = QtGui.QIcon()
        icon64.addPixmap(QtGui.QPixmap("Pics/sol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.music.setIcon(icon64)
        self.music.setIconSize(QtCore.QSize(35, 35))
        self.music.setObjectName("music")
        self.gridLayout_6.addWidget(self.music, 1, 1, 1, 1)
        icon65 = QtGui.QIcon()
        icon65.addPixmap(QtGui.QPixmap("Pics/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_4.addTab(self.education, icon65, "")
        self.consult = QtWidgets.QWidget()
        self.consult.setObjectName("consult")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.consult)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.law = QtWidgets.QCheckBox(self.consult)
        icon66 = QtGui.QIcon()
        icon66.addPixmap(QtGui.QPixmap("Pics/law.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.law.setIcon(icon66)
        self.law.setIconSize(QtCore.QSize(35, 35))
        self.law.setObjectName("law")
        self.horizontalLayout_11.addWidget(self.law)
        self.psychology = QtWidgets.QCheckBox(self.consult)
        icon67 = QtGui.QIcon()
        icon67.addPixmap(QtGui.QPixmap("Pics/psychology.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.psychology.setIcon(icon67)
        self.psychology.setIconSize(QtCore.QSize(35, 35))
        self.psychology.setObjectName("psychology")
        self.horizontalLayout_11.addWidget(self.psychology)
        self.graduation = QtWidgets.QCheckBox(self.consult)
        icon68 = QtGui.QIcon()
        icon68.addPixmap(QtGui.QPixmap("Pics/graduation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.graduation.setIcon(icon68)
        self.graduation.setIconSize(QtCore.QSize(35, 35))
        self.graduation.setObjectName("graduation")
        self.horizontalLayout_11.addWidget(self.graduation)
        self.diet = QtWidgets.QCheckBox(self.consult)
        icon69 = QtGui.QIcon()
        icon69.addPixmap(QtGui.QPixmap("Pics/food.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.diet.setIcon(icon69)
        self.diet.setIconSize(QtCore.QSize(35, 35))
        self.diet.setObjectName("diet")
        self.horizontalLayout_11.addWidget(self.diet)
        icon70 = QtGui.QIcon()
        icon70.addPixmap(QtGui.QPixmap("Pics/consulting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_4.addTab(self.consult, icon70, "")
        self.events = QtWidgets.QWidget()
        self.events.setObjectName("events")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.events)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fingerfood = QtWidgets.QCheckBox(self.events)
        icon71 = QtGui.QIcon()
        icon71.addPixmap(QtGui.QPixmap("Pics/sandwich.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fingerfood.setIcon(icon71)
        self.fingerfood.setIconSize(QtCore.QSize(40, 40))
        self.fingerfood.setObjectName("fingerfood")
        self.horizontalLayout_7.addWidget(self.fingerfood)
        self.photo = QtWidgets.QCheckBox(self.events)
        icon72 = QtGui.QIcon()
        icon72.addPixmap(QtGui.QPixmap("Pics/photography.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.photo.setIcon(icon72)
        self.photo.setIconSize(QtCore.QSize(40, 40))
        self.photo.setObjectName("photo")
        self.horizontalLayout_7.addWidget(self.photo)
        self.musicians = QtWidgets.QCheckBox(self.events)
        icon73 = QtGui.QIcon()
        icon73.addPixmap(QtGui.QPixmap("Pics/piano.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.musicians.setIcon(icon73)
        self.musicians.setIconSize(QtCore.QSize(40, 40))
        self.musicians.setObjectName("musicians")
        self.horizontalLayout_7.addWidget(self.musicians)
        icon74 = QtGui.QIcon()
        icon74.addPixmap(QtGui.QPixmap("Pics/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_4.addTab(self.events, icon74, "")
        self.emergency = QtWidgets.QWidget()
        self.emergency.setObjectName("emergency")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.emergency)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.key = QtWidgets.QCheckBox(self.emergency)
        icon75 = QtGui.QIcon()
        icon75.addPixmap(QtGui.QPixmap("Pics/password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.key.setIcon(icon75)
        self.key.setIconSize(QtCore.QSize(40, 40))
        self.key.setObjectName("key")
        self.horizontalLayout_10.addWidget(self.key)
        self.lab_test = QtWidgets.QCheckBox(self.emergency)
        icon76 = QtGui.QIcon()
        icon76.addPixmap(QtGui.QPixmap("Pics/lab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lab_test.setIcon(icon76)
        self.lab_test.setIconSize(QtCore.QSize(35, 35))
        self.lab_test.setObjectName("lab_test")
        self.horizontalLayout_10.addWidget(self.lab_test)
        self.disinfect = QtWidgets.QCheckBox(self.emergency)
        icon77 = QtGui.QIcon()
        icon77.addPixmap(QtGui.QPixmap("Pics/disinfection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.disinfect.setIcon(icon77)
        self.disinfect.setIconSize(QtCore.QSize(35, 35))
        self.disinfect.setObjectName("disinfect")
        self.horizontalLayout_10.addWidget(self.disinfect)
        self.car_door = QtWidgets.QCheckBox(self.emergency)
        icon78 = QtGui.QIcon()
        icon78.addPixmap(QtGui.QPixmap("Pics/car-door.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.car_door.setIcon(icon78)
        self.car_door.setIconSize(QtCore.QSize(35, 35))
        self.car_door.setObjectName("car_door")
        self.horizontalLayout_10.addWidget(self.car_door)
        icon79 = QtGui.QIcon()
        icon79.addPixmap(QtGui.QPixmap("Pics/alarm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_4.addTab(self.emergency, icon79, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 224, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.add_box = QtWidgets.QLineEdit(self.tab)
        self.add_box.setGeometry(QtCore.QRect(250, 40, 113, 31))
        self.add_box.setObjectName("add_box")
        self.add_button = QtWidgets.QPushButton(self.tab)
        self.add_button.setGeometry(QtCore.QRect(400, 40, 71, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("color: rgb(255, 255, 255);\n"
        "background-color: rgb(0, 0, 127);\n"
        "font: 75 10pt \"Arial\";")
        self.add_button.setObjectName("add_button")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(510, 10, 451, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 441, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        icon80 = QtGui.QIcon()
        icon80.addPixmap(QtGui.QPixmap("Pics/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_4.addTab(self.tab, icon80, "")
        self.verticalLayout.addWidget(self.tabWidget_4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.description = QtWidgets.QLineEdit(self.centralwidget)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.done = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.done.setFont(font)
        self.done.setStyleSheet("color: rgb(255, 255, 255);\n"
        "background-color: rgb(0, 0, 127);\n"
        "font: 75 17pt \"Arial\";")
        self.done.setObjectName("done")
        self.verticalLayout.addWidget(self.done)
        Services_2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Services_2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        Services_2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Services_2)
        self.statusbar.setObjectName("statusbar")
        Services_2.setStatusBar(self.statusbar)
        self.actionUS = QtWidgets.QAction(Services_2)
        self.actionUS.setObjectName("actionUS")
        self.actionThis_App = QtWidgets.QAction(Services_2)
        self.actionThis_App.setObjectName("actionThis_App")
        self.actionVia_Email = QtWidgets.QAction(Services_2)
        self.actionVia_Email.setObjectName("actionVia_Email")
        self.retranslateUi(Services_2)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Services_2)

        self.Services_2 = Services_2

        self.done.clicked.connect(self.All_Services)
        self.add_button.clicked.connect(self.new_service)

    def new_service(self):
        conn= sqlite3.connect("Employers.db")
        c = conn.cursor()
        d = conn.cursor()
        d.execute("SELECT * FROM service WHERE Name=(?)",(self.username,))
        count = 0

        for row in d.fetchall():
            if row[1]== self.add_box.text():
                self.warning_popup()
                count += 1

        if count==0:
            c.execute("""INSERT INTO service VALUES (?, ?);""", (self.username, self.add_box.text()))
            self.show_popup()
            
        conn.commit()

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Ok")
        msg.setText("Your service has been added successfully.\n Thanks for your service.")
        msg.setIcon(QMessageBox.Information)

        x = msg.exec_()

    def warning_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Warning")
        msg.setText("You Already have this service")
        msg.setIcon(QMessageBox.Warning)

        x = msg.exec_()

    def All_Services(self):
        conn= sqlite3.connect("Employers.db")
        c = conn.cursor()
        d = conn.cursor()

        allS=[self.cooking, self.catering, self.hcleaning, self.bcleaning, self.laundry, self.inspraying,
            self.cool, self.heat, self.water, self.gas, self.refinary, self.bigappliance,
            self.building, self.wood, self.parquet, self.ceramic, self.plastering, self.painting, self.welding, self.door, self.interior_d,
            self.outspraying, self.outdoor_d, self.gardening, self.laptop, self.tablet, self.game, self.wire, self.generator, self.s_alarm,
            self.s_camera, self.fix_car, self.carwash, self.furniture, self.delivery, self.sewing, self.restoration, self.hair,
            self.makeup, self.nails, self.injection, self.nanny, self.elder, self.patient, self.grooming, self.walking, self.train,
            self.vet, self.all_grades, self.enterance, self.university, self.music, self.software, self.law, self.graduation, self.psychology,
            self.diet, self.fingerfood, self.photo, self.musicians, self.key, self.disinfect, self.lab_test, self.car_door ]

        d.execute("SELECT * FROM service WHERE Name=(?)",(self.username,))
        count = 0

        for row in d.fetchall():
            for i in range (len(allS)):
                if allS[i].isChecked():
                    if allS[i].text()== row[1]:
                        print("You Already have this service")
                        count += 1

        if count==0:
            for j in range (len(allS)):
                if allS[j].isChecked():
                    c.execute("""
                    INSERT INTO service VALUES (?, ?);""", (self.username, allS[j].text()))
        
        conn.commit()

        if self.description.text() != '':
            c.execute(""" INSERT INTO details VALUES (?, ?);""", (self.username, self.description.text()))
            conn.commit()

        self.Services_2.close()

    def retranslateUi(self, Services_2):
        _translate = QtCore.QCoreApplication.translate
        Services_2.setWindowTitle(_translate("Services_2", "Services_2"))
        self.cooking.setText(_translate("Services_2", "Cooking"))
        self.hcleaning.setText(_translate("Services_2", "House Cleaning"))
        self.bcleaning.setText(_translate("Services_2", "Building Cleaning"))
        self.inspraying.setText(_translate("Services_2", "Indoor Spraying"))
        self.catering.setText(_translate("Services_2", "Catering"))
        self.laundry.setText(_translate("Services_2", "Laundry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.clean), _translate("Services_2", "Cleaning and Catering"))
        self.cool.setText(_translate("Services_2", "Cooling System"))
        self.water.setText(_translate("Services_2", "Water Plumbing"))
        self.gas.setText(_translate("Services_2", "Gas Plumbing"))
        self.heat.setText(_translate("Services_2", "Heating System"))
        self.refinary.setText(_translate("Services_2", "Water Refinary"))
        self.bigappliance.setText(_translate("Services_2", "Big Appliance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home), _translate("Services_2", "Install and Repair Home Appliance"))
        self.building.setText(_translate("Services_2", "Building"))
        self.welding.setText(_translate("Services_2", "Smithery and Welding"))
        self.painting.setText(_translate("Services_2", "Painting"))
        self.parquet.setText(_translate("Services_2", "Wallpapers/ Parquetry"))
        self.plastering.setText(_translate("Services_2", "Plastering"))
        self.wood.setText(_translate("Services_2", "Woodworking"))
        self.door.setText(_translate("Services_2", "Doors and Windows"))
        self.ceramic.setText(_translate("Services_2", "Ceramic and Tiling"))
        self.interior_d.setText(_translate("Services_2", "Interior Design"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.decor), _translate("Services_2", "Decorating and Reconstruction"))
        self.outspraying.setText(_translate("Services_2", "Garden Spraying"))
        self.outdoor_d.setText(_translate("Services_2", "Outdoor Design"))
        self.gardening.setText(_translate("Services_2", "Gardening"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.garden), _translate("Services_2", "Garden"))
        self.laptop.setText(_translate("Services_2", "Laptop Reparing"))
        self.tablet.setText(_translate("Services_2", "Mobile/ Tablet Reparing"))
        self.game.setText(_translate("Services_2", "Game Console Repairing"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.digital), _translate("Services_2", "Digital and Electronical Services"))
        self.wire.setText(_translate("Services_2", "Wiring"))
        self.generator.setText(_translate("Services_2", "Generators"))
        self.s_alarm.setText(_translate("Services_2", "Security Alarms"))
        self.s_camera.setText(_translate("Services_2", "Security Camera"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.elctric), _translate("Services_2", "Elecrical Working"))
        self.fix_car.setText(_translate("Services_2", "Repairing"))
        self.carwash.setText(_translate("Services_2", "Car Wash "))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.car), _translate("Services_2", "Cars"))
        self.furniture.setText(_translate("Services_2", "Home Furniture"))
        self.delivery.setText(_translate("Services_2", "Packages "))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.shipment), _translate("Services_2", "Shipment"))
        self.sewing.setText(_translate("Services_2", "Sewing"))
        self.restoration.setText(_translate("Services_2", "Clothing Restoration"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.clothes), _translate("Services_2", "Clothes"))
        self.hair.setText(_translate("Services_2", "Hair"))
        self.makeup.setText(_translate("Services_2", "Make-up"))
        self.nails.setText(_translate("Services_2", "Nails"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.beauty), _translate("Services_2", "Beauty"))
        self.injection.setText(_translate("Services_2", "Injections/ Bandages/ Stiches"))
        self.elder.setText(_translate("Services_2", "Elderly Nursing and Care"))
        self.nanny.setText(_translate("Services_2", "Nanny"))
        self.patient.setText(_translate("Services_2", "Patient Care"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.medical), _translate("Services_2", "Medical and Nursing"))
        self.grooming.setText(_translate("Services_2", "Grooming"))
        self.walking.setText(_translate("Services_2", "Walking"))
        self.train.setText(_translate("Services_2", "Training"))
        self.vet.setText(_translate("Services_2", "Veterinary"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.pets), _translate("Services_2", "Pets"))
        self.all_grades.setText(_translate("Services_2", "Teaching All Grades"))
        self.software.setText(_translate("Services_2", "Important Sofwares/ Programming"))
        self.enterance.setText(_translate("Services_2", "Enterance Exam"))
        self.university.setText(_translate("Services_2", "Teaching University Courses"))
        self.music.setText(_translate("Services_2", "Music"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.education), _translate("Services_2", "Education"))
        self.law.setText(_translate("Services_2", "Law"))
        self.psychology.setText(_translate("Services_2", "Psychology"))
        self.graduation.setText(_translate("Services_2", "Education"))
        self.diet.setText(_translate("Services_2", "Food and Diet"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.consult), _translate("Services_2", "Consulting"))
        self.fingerfood.setText(_translate("Services_2", "Finger Food"))
        self.photo.setText(_translate("Services_2", "Photographing"))
        self.musicians.setText(_translate("Services_2", "Musician"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.events), _translate("Services_2", "Meetings and Events"))
        self.key.setText(_translate("Services_2", "Key Makeing"))
        self.lab_test.setText(_translate("Services_2", "Medical Lab Tests"))
        self.disinfect.setText(_translate("Services_2", "Disinfec Home and Workplace"))
        self.car_door.setText(_translate("Services_2", "Car Opening"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.emergency), _translate("Services_2", "Emergencies"))
        self.label_4.setText(_translate("Services_2", "Do you want to add any other services?"))
        self.add_button.setText(_translate("Services_2", "Add"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab), _translate("Services_2", "Other"))
        self.label_5.setText(_translate("Services_2", "Anything else that we should know? for example what grade do you want to teach or what strument do you play. Please write it down in the text box below:"))
        self.done.setText(_translate("Services_2", "Done!"))
        self.actionUS.setText(_translate("Services_2", "Us!"))
        self.actionThis_App.setText(_translate("Services_2", "This App!"))
        self.actionVia_Email.setText(_translate("Services_2", "Via Email"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Services_2 = QtWidgets.QMainWindow()
    ui = Ui_Services_2()
    ui.setupUi(Services_2,'None')
    Services_2.show()
    sys.exit(app.exec_())
